'use client';

import { useEffect } from 'react';
import { flushQueue, registerBackgroundSync } from '@/lib/db';

export function ServiceWorkerRegistrar() {
  useEffect(() => {
    if (typeof window === 'undefined' || !('serviceWorker' in navigator)) return;

    let refreshing = false;

    // Reload smoothly when a new service worker activates
    navigator.serviceWorker.addEventListener('controllerchange', () => {
      if (refreshing) return;
      refreshing = true;
      window.location.reload();
    });

    // Register /sw.js generated by scripts/build-sw.mjs
    navigator.serviceWorker
      .register('/sw.js', { scope: '/' })
      .then((registration) => {
        // Check for updates periodically and on registration
        registration.update().catch(() => {});

        // Register background sync
        registerBackgroundSync();

        // Check if there is an update waiting
        if (registration.waiting) {
          registration.waiting.postMessage({ type: 'SKIP_WAITING' });
        }

        registration.addEventListener('updatefound', () => {
          const installingWorker = registration.installing;
          if (installingWorker) {
            installingWorker.addEventListener('statechange', () => {
              if (
                installingWorker.state === 'installed' &&
                navigator.serviceWorker.controller
              ) {
                // New update available, activate it
                installingWorker.postMessage({ type: 'SKIP_WAITING' });
              }
            });
          }
        });
      })
      .catch((err) => {
        // In local development or if sw.js is not yet built, warn gracefully
        console.info('[sw] Service worker registration note:', err?.message || err);
      });

    // Listen for background sync triggers sent from the service worker
    const onMessage = (event: MessageEvent) => {
      if (event.data?.type === 'CROP_SYNC_TRIGGER') {
        flushQueue().catch(() => {});
      }
    };
    navigator.serviceWorker.addEventListener('message', onMessage);

    // Update service worker when window regains focus
    const onFocus = () => {
      navigator.serviceWorker.getRegistration().then((reg) => {
        reg?.update().catch(() => {});
      });
    };
    window.addEventListener('focus', onFocus);

    return () => {
      navigator.serviceWorker.removeEventListener('message', onMessage);
      window.removeEventListener('focus', onFocus);
    };
  }, []);

  return null;
}
